cluster:
  name: ta-sgh-vxlan-sidecarless-cls

cni:
  chainingMode: generic-veth
  customConf: true
  configMap: cni-configuration
  confPath: /etc/cni/net.d/calico
  exclusive: false

routingMode: native
kubeProxyReplacement: "false"
enableIPv4Masquerade: false
enableIdentityMark: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: helm
    server:
      extraDnsNames:
        - "*.ta-sgh-vxlan-sidecarless-cls.hubble-grpc.cilium.io"
